version: "3.6"
services:
  smarkio-case-mysql:
    image: mysql:8.0.20
    container_name: smarkio-case-mysql
    volumes:
      - .:/smarkio-case
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    networks:
      - smarkio-case-network

  smarkio-case-api:
    build:
      context: .
      dockerfile: docker/smarkio-case-api.dockerfile
    container_name: smarkio-case-api
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:3333
    depends_on:
      - "smarkio-case-mysql"
    networks:
      - smarkio-case-network

networks:
  smarkio-case-network:
    driver: bridge
